version: '2'
services:
    hermannotes-app:
        image: hermannotes
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hermannotes-postgresql:5432/hermannotes
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hermannotes-postgresql:
        extends:
            file: postgresql.yml
            service: hermannotes-postgresql
